@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "3P Application" as A
participant "Music 3P api" as B

A -> B: call /browse
B --> A: return response

A -> B: call /browse/{type}/{id}
B --> A: return response

@enduml
